modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/ate47/AtianCore/issues"
[[mods]]
	modId="atiancore"
	version="1.0"
	displayName="Atian Core"
	displayURL="https://github.com/ate47/AtianCore"
	logoFile="logo.png"
	authors="ATE47"
	description="Some tools to create abstract mods."

[[dependencies.atiancore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"
